apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: testlinkerd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
  - host: testlinkerd.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 8080
      # - path: /sa
      #   backend:
      #     serviceName: another-svc
      #     servicePort: 8080