apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: testlinkerd
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: testlinkerd
    app.kubernetes.io/version: v10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: testlinkerd/web
        imagePullPolicy: IfNotPresent
        args:
        - --target
        - world:50040
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: testlinkerd
spec:
  selector:
    app: web
  ports:
  - name: http
    port: 8080
    targetPort: 8080